#!/usr/bin/env Rscript

############################################################
# Script Name : 09_tximport.R
#
# Description :
#   Import Salmon transcript quantifications using tximport
#   and generate gene-level count matrices for downstream
#   differential expression analysis.
#
# Workflow:
#
#   Salmon quant.sf files
#              |
#              v
#        tximport()
#              |
#              v
#     gene-level matrices
#
#
# Inputs:
#
#   1. Salmon quantification folders
#   2. tx2gene.csv generated by 08_make_tx2gene.R
#
#
# Outputs:
#
#   txi.rds
#   counts.tsv
#   abundance.tsv
#   length.tsv
#   counts.rds
#   abundance.rds
#   length.rds
#   sample_table.csv
#   tximport_summary.txt
#   sessionInfo.txt
#
#
# Project:
#   Bryophyte-PCD
#
############################################################


############################################################
# Load packages
############################################################

suppressPackageStartupMessages({

    library(tximport)
    library(readr)
    library(dplyr)

})


############################################################
# USER SETTINGS
############################################################


# Change only this section for another species


PROJECT_DIR <-
    "/Users/aakanksha/Desktop/github/Bryophyte-PCD"


SPECIES <-
    "Marchantia_polymorpha"



# Salmon output directory

SALMON_DIR <-
    "/Volumes/AakankshaHd/PCD/Marchantia/trimmed/salmon"



# tx2gene file

TX2GENE_FILE <-
    file.path(
        PROJECT_DIR,
        "references",
        SPECIES,
        "tx2gene.csv"
    )



# Output directory

OUTPUT_DIR <-
    file.path(
        PROJECT_DIR,
        "results",
        SPECIES,
        "tximport"
    )



# Log directory

LOG_DIR <-
    file.path(
        PROJECT_DIR,
        "data",
        SPECIES,
        "logs"
    )



############################################################
# Create directories
############################################################


dir.create(
    OUTPUT_DIR,
    recursive = TRUE,
    showWarnings = FALSE
)


dir.create(
    LOG_DIR,
    recursive = TRUE,
    showWarnings = FALSE
)



LOG_FILE <-
    file.path(
        LOG_DIR,
        "09_tximport.log"
    )



############################################################
# Logging
############################################################


sink(
    LOG_FILE,
    append = TRUE,
    split = TRUE
)


cat("\n")
cat("====================================================\n")
cat("TXIMPORT STARTED\n")
cat("Started :", Sys.time(), "\n")
cat("Species :", SPECIES, "\n")
cat("====================================================\n\n")



############################################################
# Input validation
############################################################


cat("Checking inputs...\n\n")



if(!file.exists(TX2GENE_FILE)){

    stop(
        "ERROR: tx2gene file not found:\n",
        TX2GENE_FILE
    )

}



if(!dir.exists(SALMON_DIR)){

    stop(
        "ERROR: Salmon directory not found:\n",
        SALMON_DIR
    )

}



cat("tx2gene file:\n")
cat(TX2GENE_FILE,"\n\n")


cat("Salmon directory:\n")
cat(SALMON_DIR,"\n\n")



############################################################
# Find Salmon quantification files
############################################################


cat("Searching for quant.sf files...\n\n")



quant_files <-
    list.files(
        path = SALMON_DIR,
        pattern = "quant\\.sf$",
        recursive = TRUE,
        full.names = TRUE
    )



if(length(quant_files) == 0){

    stop(
        "ERROR: No quant.sf files found in:\n",
        SALMON_DIR
    )

}



cat(
    "Found",
    length(quant_files),
    "Salmon quantification files\n\n"
)



############################################################
# Create sample names
############################################################


sample_names <-
    basename(
        dirname(quant_files)
    )



# Ensure unique names

if(any(duplicated(sample_names))){

    stop(
        "ERROR: Duplicate sample names detected:\n",
        paste(
            sample_names[
                duplicated(sample_names)
            ],
            collapse=", "
        )
    )

}



names(quant_files) <-
    sample_names



cat("Samples detected:\n")

print(sample_names)

cat("\n")


############################################################
# Read tx2gene table
############################################################


cat("Reading tx2gene table...\n\n")


tx2gene <-
    read_csv(
        TX2GENE_FILE,
        show_col_types = FALSE
    )



if(
    !all(
        c("transcript", "gene")
        %in%
        colnames(tx2gene)
    )
){

    stop(
        "ERROR: tx2gene file must contain columns:\n",
        "transcript, gene\n"
    )

}



cat(
    "Transcripts in tx2gene:",
    nrow(tx2gene),
    "\n"
)


cat(
    "Genes in tx2gene:",
    length(unique(tx2gene$gene)),
    "\n\n"
)



############################################################
# Check transcript compatibility
############################################################


cat("Checking Salmon transcript IDs...\n\n")


example_quant <-
    read_tsv(
        quant_files[1],
        show_col_types = FALSE
    )



if(!"Name" %in% colnames(example_quant)){

    stop(
        "ERROR: quant.sf does not contain Name column\n"
    )

}



salmon_transcripts <-
    example_quant$Name



matched <-
    sum(
        salmon_transcripts
        %in%
        tx2gene$transcript
    )



cat(
    "Example sample:",
    names(quant_files)[1],
    "\n"
)


cat(
    "Transcripts checked:",
    length(salmon_transcripts),
    "\n"
)


cat(
    "Matched transcripts:",
    matched,
    "\n\n"
)



if(matched == 0){

    stop(
        "\nERROR:\n",
        "No transcript IDs matched between Salmon and tx2gene.\n",
        "Check annotation/transcript FASTA compatibility.\n"
    )

}



############################################################
# Run tximport
############################################################


cat("Running tximport...\n\n")



txi <-
    tximport(
        files = quant_files,
        type = "salmon",
        tx2gene = tx2gene,
        countsFromAbundance = "lengthScaledTPM"
    )



cat("\ntximport completed successfully\n\n")



############################################################
# Save tximport object
############################################################


cat("Saving tximport object...\n")



saveRDS(
    txi,
    file.path(
        OUTPUT_DIR,
        "txi.rds"
    )
)



cat("Saved:",
    file.path(
        OUTPUT_DIR,
        "txi.rds"
    ),
    "\n\n"
)



############################################################
# Save matrices
############################################################


cat("Saving matrices...\n\n")



write.csv(
    txi$counts,
    file.path(
        OUTPUT_DIR,
        "counts.tsv"
    ),
    quote = FALSE
)


saveRDS(
    txi$counts,
    file.path(
        OUTPUT_DIR,
        "counts.rds"
    )
)



write.csv(
    txi$abundance,
    file.path(
        OUTPUT_DIR,
        "abundance.tsv"
    ),
    quote = FALSE
)


saveRDS(
    txi$abundance,
    file.path(
        OUTPUT_DIR,
        "abundance.rds"
    )
)



write.csv(
    txi$length,
    file.path(
        OUTPUT_DIR,
        "length.tsv"
    ),
    quote = FALSE
)


saveRDS(
    txi$length,
    file.path(
        OUTPUT_DIR,
        "length.rds"
    )
)



############################################################
# Create sample table
############################################################


cat("Creating sample table...\n\n")



sample_table <-
    data.frame(
        sample = colnames(txi$counts)
    )



write.csv(
    sample_table,
    file.path(
        OUTPUT_DIR,
        "sample_table.csv"
    ),
    row.names = FALSE
)



############################################################
# Summary
############################################################


summary_file <-
    file.path(
        OUTPUT_DIR,
        "tximport_summary.txt"
    )



sink(summary_file)



cat("tximport summary\n\n")


cat(
    "Species:\n",
    SPECIES,
    "\n\n"
)


cat(
    "Salmon directory:\n",
    SALMON_DIR,
    "\n\n"
)


cat(
    "tx2gene file:\n",
    TX2GENE_FILE,
    "\n\n"
)


cat(
    "Samples imported:\n",
    ncol(txi$counts),
    "\n\n"
)


cat(
    "Genes quantified:\n",
    nrow(txi$counts),
    "\n\n"
)


cat(
    "Generated:\n",
    Sys.time(),
    "\n"
)



sink()



############################################################
# Save session information
############################################################


sink(
    file.path(
        OUTPUT_DIR,
        "sessionInfo.txt"
    )
)


sessionInfo()


sink()



############################################################
# Finish
############################################################


cat("\n")
cat("====================================================\n")
cat("TXIMPORT COMPLETE\n")
cat("Finished :", Sys.time(), "\n")
cat("====================================================\n\n")


cat(
    "Samples imported:",
    ncol(txi$counts),
    "\n"
)


cat(
    "Genes:",
    nrow(txi$counts),
    "\n"
)


cat(
    "\nOutput directory:\n",
    OUTPUT_DIR,
    "\n"
)



sink()